version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  person_service:
    image: xom4ik/person-service:latest
    hostname: person_service
    container_name: person-service
    ports:
      - "8080:8080"
    restart: always


volumes:
  db-data: